server:
  port: 8081
dubbo:
  application:
    name: cart-consumer
  registry:
    address: zookeeper://47.95.248.0:2181
spring:
  redis:
    host: 47.95.248.0
    port: 6379
    jedis:
      pool:
        max-active: 20
